### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by Wabri** [Wabri/Spotato#1]
Create some sort of logo with a potato.

**Comment by munadikieh** [comment]
Hi @Wabri 
I,m Munadi Kiehl, Graphic Designer. This is my proposal for Potato Logo.
![Artboard 3](https://user-images.githubusercontent.com/41304326/61709508-a147dc00-ad79-11e9-982c-7b319c1bcd39.jpg)

Please give me feedback for this concept, if there any revision, please just tell me.

**Comment by Wabri** [comment]
Hi @munadikieh, thanks a lot for this awesome logo. Can I add it to the project? Do you have some sort of link where I can download this images?

I will add you to the contributors of the project as the designer of the logo :1st_place_medal:
Do you want some special references? Something like **Design by @munadikieh** or **Logo created by @munadikieh**

**Comment by munadikieh** [comment]
Hi @Wabri Thanks for accepting my logo and I'm so glad can contribute on your project. I have created PR #3 and you also can Download Original file in [GDrive](https://drive.google.com/drive/folders/1ySRbTEh4-ZJCprqoDTGlpDvLwqnTWQo4?usp=sharing). 
You can add my name to the contributors of the project as Logo created by.
Have a nice day.

Best regard,
Munadi Kiehl
